MODULE STR2INT
CONTAINS
  ELEMENTAL SUBROUTINE STOI(str, int)
    IMPLICIT NONE
    CHARACTER(len=*),INTENT(IN) :: str
    INTEGER,intent(OUT) :: int
    READ(str,*) int
  END SUBROUTINE STOI
END MODULE STR2INT


PROGRAM MAIN
  USE STR2INT
  IMPLICIT NONE
  INTEGER :: N
  INTEGER :: I = 1
  LOGICAL :: IS_EVEN
  CHARACTER(LEN=32) :: arg
  IS_EVEN = .FALSE.
  IF (IARGC() /= 1) THEN
    CALL EXIT(1)
  ENDIF
  CALL GETARG(1, arg)
  CALL STOI(arg, N)
  PRINT'("PROGRAM IFELSEISEVEN")'
  PRINT'("INTEGER :: n = ", I0)', N
  PRINT'("LOGICAL :: IS_EVEN")'
  PRINT'("IF (N == ", I0, ") THEN")', I
  PRINT'("IS_EVEN = .TRUE.")'
  DO WHILE(I <= N)
    PRINT'("ELSE IF (N == ", I0, ") THEN")', I
    IF (IS_EVEN) THEN
      PRINT'("IS_EVEN = .TRUE.")'
    ELSE
      PRINT'("IS_EVEN = .FALSE.")'
    ENDIF
    IS_EVEN = .NOT. IS_EVEN
    I = I + 1
  END DO
  PRINT'("ENDIF")'
  PRINT'("END PROGRAM IFELSEISEVEN")'
END PROGRAM MAIN
